### ISSUE TITLE
[Angular] access_token isn't added without shorcut method $http

### ISSUE THREAD

**Issue by JonathanRamier** [gomoob/oauth.js#11]
I implement a factory proxy which take an object like this

```
var bookService = {
    url: 'api/1.0/books',
    method: 'GET',
    params: {
        page: 1,
        line: 25 
    }
};
```

this factory doesn't use the shortcut method of $http service and  take the object.

```
$http(bookService);
```

when I use oauth.js, the access_token didn't add because I have the console message followed from my API

```
code: 401
message: "The access token is missing"
```

**Comment by bgaillard** [comment]
Hi @JonathanRamier, this should be fixed in the following commit : https://github.com/gomoob/oauth.js/commit/72301b36465d14bdc173d04ce3d1c04210b80ef0.

Could you test it and indicate if its working as expected now ?

Thanks

**Comment by JonathanRamier** [comment]
It works now.

**Comment by bgaillard** [comment]
@JonathanRamier Ok good news, thanks for the tests !
