### ISSUE TITLE
[Angular] DI service $delegate

### ISSUE THREAD

**Issue by JonathanRamier** [gomoob/oauth.js#14]
I bootstrap my app with object config like show in [angular bootstrap](https://docs.angularjs.org/api/ng/function/angular.bootstrap)

When I implement OAuth.init, I have the error 

```
https://docs.angularjs.org/error/$injector/strictdi?p0=function($delegate
```

To fix them, I update the code like this 

```
this._$provide.decorator(
                '$http', 
                ['$delegate', function($delegate) {
                       ...
                }]);
```

I didn't create a pull request for this issue.

**Comment by bgaillard** [comment]
Hi @JonathanRamier and thanks for this suggestion. The fix you proposed has been applied in commit  https://github.com/gomoob/oauth.js/commit/27833c41c91848caffe8b674839a37722f97e671, is it working as expected now ?

**Comment by bgaillard** [comment]
@JonathanRamier  Thanks for the tests !
